### ISSUE TITLE
"Invalid objects with current object bank settings"

### ISSUE THREAD

**Issue by NorthLake** [StapleButter/SM64DSe#1]
I've tried redownloading SM64DSe, and redownloading the game, but I keep getting the issue where "The level contains objects which aren't available with the current object bank settings, and would crash the game." However, when I start the game everything works. I get this with every level I try to edit. I'm still very new into the program, and game designing entirely, so don't throw words at me that are to difficult for me. ;P
![weird object banks](https://cloud.githubusercontent.com/assets/20684682/17178852/5551e9d0-5417-11e6-916a-681bbea73bd0.PNG)
![image](https://cloud.githubusercontent.com/assets/20684682/17178930/98b19874-5417-11e6-8b07-2b110c110c3a.png)

**Comment by Fiachra1993** [comment]
Hi, 

Sorry for the delay, I only noticed this issue today. 

You need to run SM64DSe.exe from within the "bin" directory as it is - the editor relies on certain files being in the same directory such as "objectdb.xml" which tells it which bank each object belongs to.

For SM64DS hacking tutorials and support you should see http://kuribo64.net/board/. I be quite active there so you've a much better chance of getting a quick answer.

**Comment by NorthLake** [comment]
I did. I launched the game via a shortcut leading to the exe file in the
bin directory.  It's fixed for me now, though. I don't know what I did to
fix it,  but it's fixed...
